### ISSUE TITLE
Mark's cafe incorrectly showing that it's open

### ISSUE THREAD

**Issue by joshdoman** [pennlabs/penn-mobile-server#100]
![screen shot 2017-05-13 at 5 29 09 pm](https://cloud.githubusercontent.com/assets/22065307/26029384/bb482bb8-3801-11e7-870f-9f8b51772cef.png)
![screen shot 2017-05-13 at 5 28 57 pm](https://cloud.githubusercontent.com/assets/22065307/26029385/bb4dd4e6-3801-11e7-85e4-ce0ac7e30c07.png)

**Comment by adelq** [comment]
Contact OpenData Help, they'll reach out to the appropriate people at Business Services to have this resolved. We used to have a contact at Business Services for direct contact, but they may have changed. Let me know if you still want their contact info anyways.

**Comment by adelq** [comment]
Closing because not inherent bug with the mobile server but rather with data source
