### ISSUE TITLE
Paths don't correspond to roads

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-server#36]
Should correspond to Google Maps road coordinates
![ios_simulator_screen_shot_apr_19__2015__5 07 22_pm_1024](https://cloud.githubusercontent.com/assets/929309/7221379/ce52f59c-e6b6-11e4-89d7-738b775063f9.png)

**Comment by awiss** [comment]
Penn Transit's fault!

Pennride's info if off in a similar way. I'm not fixing this manually for now. Adel is emailing the Open Transit people about it.

**Comment by awiss** [comment]
I'm closing this, were linking the two points together on the frontend.
