### ISSUE TITLE
Buses go in loops

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-server#37]
Should not be the case, bus routes definitely do not go in a loop
![ios_simulator_screen_shot_apr_15__2015__10 49 59_pm_1024](https://cloud.githubusercontent.com/assets/929309/7221361/2f87348c-e6b6-11e4-81b8-a55a0aea04d7.png)

**Comment by sachabest** [comment]
derp

**Comment by awiss** [comment]
The issue here is that google maps interprets the lat long as being on the wrong street. Since there are once way we get this ridiculous result. At this point, we are just copying the pennrides route info.

**Comment by awiss** [comment]
Leaving this open till we resolve this.

**Comment by awiss** [comment]
Fixed and Deployed https://github.com/pennlabs/penn-mobile-server/pull/41
