### ISSUE TITLE
Buses go in very winded paths

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-server#38]
![ios_simulator_screen_shot_apr_15__2015__10 48 53_pm_1024](https://cloud.githubusercontent.com/assets/929309/7221378/c163474c-e6b6-11e4-9ed5-a24cb6982853.png)

**Comment by awiss** [comment]
See https://github.com/pennlabs/penn-mobile-server/issues/37#issuecomment-95365283

**Comment by awiss** [comment]
Keeping this closed. Leaving #37 open to track our manual replacement of route info
