### ISSUE TITLE
Implement Penn Canvas API

### ISSUE THREAD

**Issue by afischer** [pennlabs/penn-mobile-server#67]
[Full API Docs](https://canvas.instructure.com/doc/api/index.html)
We could use this to grab courses and upcoming assignments for any user, especially now since we have SSO enabled (almost, see #66).

**Comment by adelq** [comment]
As it stands, implementing SSO on our end does not help with Canvas authentication. In order to have a fully automated Canvas OAuth session, we need to register a client application with whoever the Canvas administrators are. See https://canvas.instructure.com/doc/api/file.oauth.html#oauth2-flow-0
