### ISSUE TITLE
Disable CORS

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-server#78]

**Comment by adamdom** [comment]
http://stackoverflow.com/questions/27365303/what-is-the-issue-cors-is-coming-to-solve

**Comment by adelq** [comment]
So, I looked into this a bit more. We should either re-disable CORS because anyone can now fetch a user's authentication token. The more nuanced solutions that require more development are 1) allow CORS selectively on non-sensitive endpoints, or 2) move authentication to another domain which is hard because we will need to do the entire setup with PennKey once again. I'm re-enabling CORS because auth is currently live, but leaving this issue closed since it's resolved. Instead, I'll re-open a separate issue to look into these options.
