### ISSUE TITLE
Dining Menus down

### ISSUE THREAD

**Issue by esqu1** [pennlabs/penn-mobile-server#98]
At http://api.pennlabs.org/dining/daily_menu/1 and http://api.pennlabs.org/dining/weekly_menu/1

![image](https://cloud.githubusercontent.com/assets/7027037/25297358/4264c348-26bb-11e7-89d5-25b8c1732ac1.png)

**Comment by adelq** [comment]
No, you just have to provide a valid ID. Invalid hall ID will always fail.
